checkoutLocation: "ansible_collections/community/general"
workspaceLocation: "ansible_collections/community/general"
tasks:
  - init: setup env
    command: |
      python -m pip install ansible

ports:
  - port: 3000
    onOpen: open-preview
