checkoutLocation: "ansible_collections/community/general"
workspaceLocation: "ansible_collections/community/general"
tasks:
  - before: python -m pip install ansible

ports:
  - port: 3000
    onOpen: open-preview
  - port: 8880
    onOpen: ignore
